spring:
  application:
    name: carrefour
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

  config:
    import: optional:file:.env[.properties]

  email:
    user: ${EMAIL_USER}
    password: ${EMAIL_PASSWORD}

